[tool.poetry]
name = "qha"
version = "1.0.18"
description = ""
authors = ["Qi Zhang <singularitti@outlook.com>"]

[tool.poetry.dependencies]
python = "^3.6"
lazy_property = "^0.0.1"
mpmath = "^1.1"
numba = "^0.44.0"
pandas = "^0.24.2"
scientific-string = "^0.0.3"
scipy = "^1.3"
text-stream = "^0.2.0"
pyyaml = "^5.1"
matplotlib = "^3.1"
seaborn = "^0.9.0"
bigfloat = "^0.3.0"

[tool.poetry.dev-dependencies]
pytest = "^3.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
